name: genv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - ipython
  - matplotlib
  - pytorch
  - scikit-learn
  - nltk
  - pandas
  - tqdm
  - stop-words
  - spacy
  - pip:
    - transformers=2.10
    - wmd
